//DADOS PRIMITIVOS

let oi; // VALOR UNDEFINED -> NÃO APONTA PARA NENHUMN LUGAR DA MEMORIA
const sobrenomeAluno = null; // NULO -> NÃO APONTA PARA NENHUM LUGAR DA MEMORIA // É UM VALOR QUE O USUSARIO PODE DEFINIR

const aprovado = true;// VALORES BOOLEAN -> TRUE OU FALSE (LÓGICO)



