// VARIAVEIS 

//let MELHOR VARIAVEL, POIS NAO FOGE DO ESCOPO LOCAL PARA O ESCOPO GLOBAL

//var  INFELIZMENTE ELA FOGE DO ESCOPO LOCAL PARA O GLOBAL E ISSO PODE DAR CONFLITO

//const  É UMA VARIAVEL CONSTANTE, QUE O VALOR É SEMPRE O MESMO

//VARIAVEIS PRECISAM TER NOMES SIGNIFICATIVOS E EXPLICITOS

// É UTILIZADO CAMELCASE



